services:

  postgres:
    image: postgres:16
    container_name: lotofacil-postgres

    environment:
      POSTGRES_DB: lotofacil
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - type: bind
        source: ./data/postgres
        target: /var/lib/postgresql/data
